spring.application.name=linkvault-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/linkvault}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:linkvault}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:linkvault}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
